//setup
set_attack_value(AT_UTILT, AG_SPRITE, sprite_get("utilt"));
set_attack_value(AT_UTILT, AG_HURTBOX_SPRITE, sprite_get("utilt_hurt"));
set_attack_value(AT_UTILT, AG_NUM_WINDOWS, 11);
set_attack_value(AT_UTILT, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_UTILT, AG_CATEGORY, 2);

//hitboxes
set_num_hitboxes(AT_UTILT, 9);
//#1 - #8, flapping hitboxes
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_Y, -45);
set_hitbox_value(AT_UTILT, 1, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 1, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 1, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 1, HG_ANGLE, 270);
set_hitbox_value(AT_UTILT, 1, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 1, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 1, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 1, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UTILT, 1, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 2, HG_WINDOW, 3);
set_hitbox_value(AT_UTILT, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_Y, -12);
set_hitbox_value(AT_UTILT, 2, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 2, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 2, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 2, HG_ANGLE, 90);
set_hitbox_value(AT_UTILT, 2, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 2, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 2, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 2, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_UTILT, 2, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 3, HG_WINDOW, 4);
set_hitbox_value(AT_UTILT, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_Y, -45);
set_hitbox_value(AT_UTILT, 3, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 3, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 3, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 3, HG_ANGLE, 270);
set_hitbox_value(AT_UTILT, 3, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 3, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 3, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 3, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 3, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_UTILT, 3, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 4, HG_WINDOW, 5);
set_hitbox_value(AT_UTILT, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_Y, -12);
set_hitbox_value(AT_UTILT, 4, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 4, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 4, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 4, HG_ANGLE, 90);
set_hitbox_value(AT_UTILT, 4, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 4, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 4, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 4, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_GROUP, 4);
set_hitbox_value(AT_UTILT, 4, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 5, HG_WINDOW, 6);
set_hitbox_value(AT_UTILT, 5, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_Y, -45);
set_hitbox_value(AT_UTILT, 5, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 5, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 5, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 5, HG_ANGLE, 270);
set_hitbox_value(AT_UTILT, 5, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 5, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 5, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 5, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_GROUP, 5);
set_hitbox_value(AT_UTILT, 5, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 6, HG_WINDOW, 7);
set_hitbox_value(AT_UTILT, 6, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 6, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_Y, -12);
set_hitbox_value(AT_UTILT, 6, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 6, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 6, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 6, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 6, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 6, HG_ANGLE, 90);
set_hitbox_value(AT_UTILT, 6, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 6, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 6, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 6, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_GROUP, 6);
set_hitbox_value(AT_UTILT, 6, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 7, HG_WINDOW, 8);
set_hitbox_value(AT_UTILT, 7, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 7, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 7, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 7, HG_HITBOX_Y, -45);
set_hitbox_value(AT_UTILT, 7, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 7, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 7, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 7, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 7, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 7, HG_ANGLE, 270);
set_hitbox_value(AT_UTILT, 7, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 7, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 7, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 7, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 7, HG_HITBOX_GROUP, 7);
set_hitbox_value(AT_UTILT, 7, HG_ANGLE_FLIPPER, 4);

set_hitbox_value(AT_UTILT, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 8, HG_WINDOW, 9);
set_hitbox_value(AT_UTILT, 8, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 8, HG_LIFETIME, 4);
set_hitbox_value(AT_UTILT, 8, HG_HITBOX_X, 6);
set_hitbox_value(AT_UTILT, 8, HG_HITBOX_Y, -12);
set_hitbox_value(AT_UTILT, 8, HG_WIDTH, 72);
set_hitbox_value(AT_UTILT, 8, HG_HEIGHT, 38);
set_hitbox_value(AT_UTILT, 8, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 8, HG_DAMAGE, 1);
set_hitbox_value(AT_UTILT, 8, HG_ANGLE, 90);
set_hitbox_value(AT_UTILT, 8, HG_BASE_KNOCKBACK, 0.15);
set_hitbox_value(AT_UTILT, 8, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_UTILT, 8, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_UTILT, 8, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 8, HG_HITBOX_GROUP, 8);
set_hitbox_value(AT_UTILT, 8, HG_ANGLE_FLIPPER, 4);
//#9, finisher
set_hitbox_value(AT_UTILT, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 9, HG_WINDOW, 10);
set_hitbox_value(AT_UTILT, 9, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UTILT, 9, HG_LIFETIME, 8);
set_hitbox_value(AT_UTILT, 9, HG_HITBOX_X, 5);
set_hitbox_value(AT_UTILT, 9, HG_HITBOX_Y, -47);
set_hitbox_value(AT_UTILT, 9, HG_WIDTH, 58);
set_hitbox_value(AT_UTILT, 9, HG_HEIGHT, 65);
set_hitbox_value(AT_UTILT, 9, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 9, HG_PRIORITY, 1);
set_hitbox_value(AT_UTILT, 9, HG_DAMAGE, 5);
set_hitbox_value(AT_UTILT, 9, HG_ANGLE, 90);
set_hitbox_value(AT_UTILT, 9, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_UTILT, 9, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_UTILT, 9, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_UTILT, 9, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_UTILT, 9, HG_HITBOX_GROUP, 9);
set_hitbox_value(AT_UTILT, 1, HG_ANGLE_FLIPPER, 3);

//startup
set_window_value(AT_UTILT, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UTILT, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_UTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);
//flaps! next 8 windows
set_window_value(AT_UTILT, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_UTILT, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 2, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 2, AG_WINDOW_VSPEED, -4);
set_window_value(AT_UTILT, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_UTILT, 2, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 3, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_UTILT, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 3, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 3, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 4, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 4, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_UTILT, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 4, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 4, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 5, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 5, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_UTILT, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 5, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 5, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 5, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 6, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 6, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_UTILT, 6, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 6, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 6, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 6, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 7, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 7, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_UTILT, 7, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 7, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 7, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 7, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 8, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 8, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_UTILT, 8, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 8, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 8, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 8, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_window_value(AT_UTILT, 9, AG_WINDOW_LENGTH, 4);
set_window_value(AT_UTILT, 9, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_UTILT, 9, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 9, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UTILT, 9, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UTILT, 9, AG_WINDOW_CUSTOM_GRAVITY, 0.4);
//finsher
set_window_value(AT_UTILT, 10, AG_WINDOW_LENGTH, 8);
set_window_value(AT_UTILT, 10, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_UTILT, 10, AG_WINDOW_ANIM_FRAMES, 1);
//recovery
set_window_value(AT_UTILT, 11, AG_WINDOW_LENGTH, 15);
set_window_value(AT_UTILT, 11, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_UTILT, 11, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UTILT, 11, AG_WINDOW_HAS_WHIFFLAG, 1);